hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        twitch:
            type: twitch
            client_id: '%env(TWITCH_CLIENT_ID)%'
            client_secret: '%env(TWITCH_CLIENT_SECRET)%'
            scope: user_read
