version: "3.5"

services:
  web:
    image: webdevops/php-nginx:7.3
    working_dir: /app
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: Europe/Paris
      PHP_DISPLAY_ERRORS: 1

  db:
    image: mysql:5.7
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: twitch-app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
